projectr/managerauth/urls.py
from django.urls import path
from .views import start, register, login

app_name = 'managerauth'

urlpatterns = [
    path('start/', start, name='start'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
]

projectr/projectr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('managerauth.urls')),
    path('admin/', admin.site.urls),
]

projectr/managerauth/models.py
from django.db import models

# Create your models here.
class Manager(models.Model):
    manager_name = models.CharField(max_length=200)
    manager_email = models.EmailField(unique=True)
    manager_hpass = models.CharField(max_length=200)

    def __str__(self):
        return self.manager_name + ', ' + self.manager_email

projectr/managerauth/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from .models import Manager

# Create your views here.
def login(request):
    if request.method == 'POST':
        email = request.POST.get('login-email', 'undefined')
        hpass = request.POST.get('login-password', 'undefined')

        qs = Manager.objects.filter(manager_email=email)

        context = {
            'email' : email
        }

        if not qs:
            return render(request, 'managerauth/noaccount.html', context=context)
        
        if hpass != qs[0].manager_hpass:
            return render(request, 'managerauth/invalidpassword.html', context=context)
        
        # Render logged
        return HttpResponse('Login well done!')

    raise Http404()

def register(request):
    if request.method == 'POST':
        name = request.POST.get('register-name', 'undefined')
        email = request.POST.get('register-email', 'undefined')
        hpass = request.POST.get('register-password', 'undefined')
        
        manager_with_email = Manager.objects.filter(manager_email=email)
        # print('\n\n\n{}\n\n\n'.format(manager_with_email))

        context = {
            'email' : email,
        }

        if manager_with_email:
            return render(request, 'managerauth/onregisteremail.html', context=context)
        
        manager = Manager(
            manager_name = name,
            manager_email = email,
            manager_hpass = hpass
        )

        manager.save()

        return render(request, 'managerauth/onregister.html', context=context)

    raise Http404()

def start(request):
    return render(request, 'managerauth/start.html')

projectr/managerauth/templates/managerauth/invalidpassword.html
{% load static %}
<link rel="stylesheet" href="{% static 'managerauth/styles.css' %}">
<script type="text/javascript" src="{% static 'managerauth/hash.js' %}"></script>
<div>
    <p>Invalid password for accout {{email}}!</p>
</div>
{% include 'managerauth/login.html' %}

projectr/managerauth/templates/managerauth/login.html
{% load static %}
<div class="form-box">
    <h1>Manager login</h1>
    <form action="{% url 'managerauth:login' %}" method="post" id="login-form">
        {% csrf_token %}     
        <label for="login-email">Email</label>
        <input id="login-email" type="email" name="login-email">
      
        <label for="login-password">Password</label>
        <input id="login-password" type="password" name="login-password">
        <input class="button-primary" type="submit" value="Login" />  
    </form>
</div>
<script type="text/javascript" src="{% static 'managerauth/login.js' %}"></script>

projectr/managerauth/templates/managerauth/noaccount.html
{% load static %}
<link rel="stylesheet" href="{% static 'managerauth/styles.css' %}">
<script type="text/javascript" src="{% static 'managerauth/hash.js' %}"></script>
<div>
    <p>No accout with {{email}} has been registred. You can register</p>
</div>
{% include 'managerauth/register.html' %}

projectr/managerauth/templates/managerauth/onregister.html
{% load static %}
<link rel="stylesheet" href="{% static 'managerauth/styles.css' %}">
<script type="text/javascript" src="{% static 'managerauth/hash.js' %}"></script>
<div>
    <p>Manager with email {{email}} has been created! Now, log in</p>
</div>
{% include 'managerauth/login.html' %}

projectr/managerauth/templates/managerauth/onregisteremail.html
{% load static %}
<link rel="stylesheet" href="{% static 'managerauth/styles.css' %}">
<script type="text/javascript" src="{% static 'managerauth/hash.js' %}"></script>
<div>
    <p>Email {{email}} is already taken! Now, log in</p>
</div>
{% include 'managerauth/login.html' %}

projectr/managerauth/templates/managerauth/register.html
{% load static %}
<div class="form-box">
    <h1>Manager register</h1>
    <form action="{% url 'managerauth:register' %}" method="post" id="register-form">
        {% csrf_token %} 
        <label for="register-name">Name</label>
        <input id="register-name" type="text" name="register-name">

        <label for="register-email">Email</label>
        <input id="register-email" type="email" name="register-email">
      
        <label for="register-password">Password</label>
        <input id="register-password" type="password" name="register-password">

        <label for="register-confirmation">Confirmation</label>
        <input id="register-confirmation" type="password" name="register-confirmation">

        <input class="button-primary" type="submit" value="Register" />  
    </form>
</div>
<script type="text/javascript" src="{% static 'managerauth/register.js' %}"></script>

projectr/managerauth/templates/managerauth/start.html
{% load static %}
<link rel="stylesheet" href="{% static 'managerauth/styles.css' %}">
<script type="text/javascript" src="{% static 'managerauth/hash.js' %}"></script>
{% include 'managerauth/login.html' %}
{% include 'managerauth/register.html' %}